image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - docker-compose up -d
  - java -Dspring.datasource.url=jdbc:mysql://localhost:3306/app -Dspring.datasource.username=app -Dspring.datasource.password=pass -jar aqa-shop.jar -P:profile=test &
  
build_script:
  - chmod +x gradlew
  - ./gradlew test -Dselenide.headless=true -Dspring.datasource.url=jdbc:mysql://localhost:3306/app -Dspring.datasource.username=app -Dspring.datasource.password=pass
